import {
  Activity,
  Code2,
  Database,
  FileText,
  Gauge,
  Layers3,
  MonitorCog,
  PackageCheck,
  RadioTower,
  TestTube2,
} from "lucide-react";

export const mfeRegistry = [
  {
    id: "main-docs",
    title: "MFE Main Docs",
    label: "Documentacao",
    status: "ativo",
    icon: FileText,
    route: "/docs",
    description: "Hub principal com paginas de arquitetura, performance, feed em tempo real e design system.",
    pages: ["Arquitetura", "Performance", "Feed em tempo real", "Design System"],
  },
  {
    id: "architecture",
    title: "MFE Architecture",
    label: "Arquitetura",
    status: "planejado",
    icon: Layers3,
    route: "/architecture",
    description: "Feature-based architecture, core compartilhado, shell, adapters, providers e contratos.",
    pages: ["Shell", "Core", "Feature modules", "Microfrontends"],
  },
  {
    id: "react-ts",
    title: "MFE React TypeScript",
    label: "React TS",
    status: "planejado",
    icon: Code2,
    route: "/react-typescript",
    description: "Hooks customizados, interfaces, enums, error boundary, suspense e lazy loading.",
    pages: ["Hooks", "Interfaces", "Error Boundary", "Lazy loading"],
  },
  {
    id: "feed",
    title: "MFE Feed Lab",
    label: "Feed",
    status: "planejado",
    icon: Activity,
    route: "/feed",
    description: "Feed estilo Twitter/Instagram com posts, midias, comentarios, curtidas e compartilhamento.",
    pages: ["Timeline", "Post card", "Comentarios", "Interacoes"],
  },
  {
    id: "performance",
    title: "MFE Performance Lab",
    label: "Performance",
    status: "planejado",
    icon: Gauge,
    route: "/performance",
    description: "Memoizacao, virtualizacao, lazy loading, code splitting, bundle strategy e otimizacao de render.",
    pages: ["Virtualizacao", "Memoizacao", "Code splitting", "Midias"],
  },
  {
    id: "data-api",
    title: "MFE Data API",
    label: "Dados API",
    status: "planejado",
    icon: Database,
    route: "/data-api",
    description: "React Query, cache, mutations, optimistic update, services, adapters e BFF simulado.",
    pages: ["Services", "React Query", "BFF", "Error handling"],
  },
  {
    id: "realtime",
    title: "MFE Realtime",
    label: "Tempo Real",
    status: "planejado",
    icon: RadioTower,
    route: "/realtime",
    description: "WebSocket, SSE, eventos, update parcial de cache e sincronizacao de feed.",
    pages: ["WebSocket", "SSE", "Eventos", "Cache sync"],
  },
  {
    id: "design-system",
    title: "MFE Design System",
    label: "Design System",
    status: "planejado",
    icon: PackageCheck,
    route: "/design-system",
    description: "Componentes base, compose layer, Tailwind, tokens, cards, botoes, modal e skeleton.",
    pages: ["Tokens", "Components", "Compose", "Patterns"],
  },
  {
    id: "quality",
    title: "MFE Quality",
    label: "Qualidade",
    status: "planejado",
    icon: TestTube2,
    route: "/quality",
    description: "Code review, SOLID, clean code, testes unitarios, Cypress e checklist tecnico.",
    pages: ["Code review", "Unit tests", "Cypress", "Clean code"],
  },
  {
    id: "infra",
    title: "MFE Infra Docs",
    label: "Infra",
    status: "planejado",
    icon: MonitorCog,
    route: "/infra",
    description: "Docker, CI/CD, deploy, containers, load balancing e estrategia de publicacao.",
    pages: ["Docker", "CI/CD", "Deploy", "Observability"],
  },
] as const;